<?php

namespace ZekyWolf\LGSQ\Helpers;

class SoftwareLink
{
    public static function get(string $type, string $ip, int $c_port, int $q_port, int $s_port): string
    {
        $links = [
            Protocols::AMERICASARMY => 'qtracker://{IP}:{S_PORT}?game=ArmyOperations&action=show',
            Protocols::AMERICASARMY3 => 'qtracker://{IP}:{S_PORT}?game=AmericasArmy3&action=show',
            Protocols::ARCASIMRACING => 'http://en.wikipedia.org/wiki/ARCA_Sim_Racing',
            Protocols::ARMA => 'qtracker://{IP}:{S_PORT}?game=ArmedAssault&action=show',
            Protocols::ARMA2 => 'http://en.wikipedia.org/wiki/ARMA_2',
            Protocols::ARMA3 => 'steam://connect/{IP}:{C_PORT}',
            Protocols::DAYZ => 'steam://connect/{IP}:{C_PORT}',
            Protocols::ALIENSVSPREDATOR2 => 'qtracker://{IP}:{S_PORT}?game=AliensversusPredator2&action=show',
            Protocols::ALIENSVSPREDATOR2_2010 => 'http://en.wikipedia.org/wiki/Aliens_vs._Predator_%28video_game%29',
            Protocols::BATTLEFIELDBADCOMPANY2 => 'http://en.wikipedia.org/wiki/Battlefield_bad_company_2',
            Protocols::BATTLEFIELDVIETNAM => 'qtracker://{IP}:{S_PORT}?game=BattlefieldVietnam&action=show',
            Protocols::BATTLEFIELD1942 => 'qtracker://{IP}:{S_PORT}?game=Battlefield1942&action=show',
            Protocols::BATTLEFIELD2 => 'qtracker://{IP}:{S_PORT}?game=Battlefield2&action=show',
            Protocols::BATTLEFIELD3 => 'https://en.wikipedia.org/wiki/Battlefield_3',
            Protocols::BATTLEFIELD4 => 'https://en.wikipedia.org/wiki/Battlefield_4',
            Protocols::BATTLEFIELD2142 => 'qtracker://{IP}:{S_PORT}?game=Battlefield2142&action=show',
            Protocols::CALLOFDUTY => 'qtracker://{IP}:{S_PORT}?game=CallOfDuty&action=show',
            Protocols::CALLOFDUTYBO3 => 'qtracker://{IP}:{S_PORT}?game=CallOfDutyBlackOps3&action=show',
            Protocols::CALLOFDUTYIW => "javascript:prompt('Put it into console:', 'connect {IP}:{C_PORT}')",
            Protocols::CALLOFDUTYOU => 'qtracker://{IP}:{S_PORT}?game=CallOfDutyUnitedOffensive&action=show',
            Protocols::CALLOFDUTYWAW => 'qtracker://{IP}:{S_PORT}?game=CallOfDutyWorldAtWar&action=show',
            Protocols::CALLOFDUTY2 => 'qtracker://{IP}:{S_PORT}?game=CallOfDuty2&action=show',
            Protocols::CALLOFDUTY4 => 'cod4://{IP}:{S_PORT}',
            Protocols::COMMANDANDCONQUER => 'qtracker://{IP}:{S_PORT}?game=CommandConquerRenegade&action=show',
            Protocols::CONANEXILES => 'steam://connect/{IP}:{C_PORT}',
            Protocols::CRYSIS => 'qtracker://{IP}:{S_PORT}?game=Crysis&action=show',
            Protocols::CRYSISWARS => 'qtracker://{IP}:{S_PORT}?game=CrysisWars&action=show',
            Protocols::CS2D => 'steam://connect/{IP}:{C_PORT}',
            Protocols::CUBE => 'http://cubeengine.com',
            Protocols::DISCORD => 'https://discord.gg/{IP}',
            Protocols::DOOMSSKULLTAG => 'http://skulltag.com',
            Protocols::DOOMZDEAMON => 'http://www.zdaemon.org',
            Protocols::DOOM3 => 'qtracker://{IP}:{S_PORT}?game=Doom3&action=show',
            Protocols::DEERHUNTER2005 => 'http://en.wikipedia.org/wiki/Deer_Hunter_(computer_game)',
            Protocols::ECO => 'http://{IP}:{Q_PORT}',
            Protocols::FACTORIO => 'steam://connect/{IP}',
            Protocols::FARCRY => 'qtracker://{IP}:{S_PORT}?game=FarCry&action=show',
            Protocols::FARMINGSIMULATOR => 'steam://connect/{IP}:{C_PORT}',
            Protocols::FEAR => 'qtracker://{IP}:{S_PORT}?game=FEAR&action=show',
            Protocols::FIVEM => 'fivem://connect/{IP}:{C_PORT}',
            Protocols::REDM => 'fivem://connect/{IP}:{C_PORT}',
            Protocols::OPERATIONFLASHPOINT => 'qtracker://{IP}:{S_PORT}?game=OperationFlashpoint&action=show',
            Protocols::FREELANCER => 'http://en.wikipedia.org/wiki/Freelancer_(computer_game)',
            Protocols::FRONTLINES => 'http://en.wikipedia.org/wiki/Frontlines:_Fuel_of_War',
            Protocols::F1CHALLENGE9902 => 'http://en.wikipedia.org/wiki/EA_Sports_F1_Series',
            Protocols::GENERICSPY1 => 'http://www.greycube.com',
            Protocols::GENERICSPY2 => 'http://www.greycube.com',
            Protocols::GENERICSPY3 => 'http://www.greycube.com',
            Protocols::GHOSTRECON => "http://en.wikipedia.org/wiki/Tom_Clancy's_Ghost_Recon",
            Protocols::GRAW => 'qtracker://{IP}:{S_PORT}?game=GhostRecon&action=show',
            Protocols::GRAW2 => "http://en.wikipedia.org/wiki/Tom_Clancy's_Ghost_Recon_Advanced_Warfighter_2",
            Protocols::GTR2 => 'http://en.wikipedia.org/wiki/GTR2',
            Protocols::HIDDENANDDANGEROUSE2 => 'http://en.wikipedia.org/wiki/Hidden_&_Dangerous_2',
            Protocols::HALFLIFE => 'steam://connect/{IP}:{C_PORT}',
            Protocols::HALFLIFEWON => 'steam://connect/{IP}:{C_PORT}',
            Protocols::HALO => 'qtracker://{IP}:{S_PORT}?game=Halo&action=show',
            Protocols::IL22STURMOVIK => 'http://en.wikipedia.org/wiki/IL-2_Sturmovik_(game)',
            Protocols::JEDIKNIGHT2 => 'qtracker://{IP}:{S_PORT}?game=JediKnight2&action=show',
            Protocols::JEDIKNIGHTJA => 'qtracker://{IP}:{S_PORT}?game=JediKnightJediAcademy&action=show',
            Protocols::JUSTCOUSE2MP => 'steam://connect/{IP}:{C_PORT}',
            Protocols::KILLINGFLOOR => 'steam://connect/{IP}:{C_PORT}',
            Protocols::KINGPIN => 'qtracker://{IP}:{S_PORT}?game=Kingpin&action=show',
            Protocols::MAFIA2MP => 'https://m2mp.de/',
            Protocols::MINECRAFT => 'minecraft://{IP}:{C_PORT}/',
            Protocols::MOHAA => 'qtracker://{IP}:{S_PORT}?game=MedalofHonorAlliedAssault&action=show',
            Protocols::MOHAA_ => 'qtracker://{IP}:{S_PORT}?game=MedalofHonorAlliedAssault&action=show',
            Protocols::MOHAAB => 'qtracker://{IP}:{S_PORT}?game=MedalofHonorAlliedAssaultBreakthrough&action=show',
            Protocols::MOHAAB_ => 'qtracker://{IP}:{S_PORT}?game=MedalofHonorAlliedAssaultBreakthrough&action=show',
            Protocols::MOHAAS => 'qtracker://{IP}:{S_PORT}?game=MedalofHonorAlliedAssaultSpearhead&action=show',
            Protocols::MOHAAS_ => 'qtracker://{IP}:{S_PORT}?game=MedalofHonorAlliedAssaultSpearhead&action=show',
            Protocols::MOHPA => 'qtracker://{IP}:{S_PORT}?game=MedalofHonorPacificAssault&action=show',
            Protocols::MOHPA_ => 'qtracker://{IP}:{S_PORT}?game=MedalofHonorPacificAssault&action=show',
            Protocols::MTA => 'mtasa://{IP}:{C_PORT}',
            Protocols::MUMBLE => 'mumble://{IP}/',
            Protocols::NASCAR2004 => 'http://en.wikipedia.org/wiki/NASCAR_Thunder_2004',
            Protocols::NEVERWINTER => 'qtracker://{IP}:{S_PORT}?game=NeverwinterNights&action=show',
            Protocols::NEVERWINTER2 => 'qtracker://{IP}:{S_PORT}?game=NeverwinterNights&action=show',
            Protocols::NEXUIZ => 'qtracker://{IP}:{S_PORT}?game=Nexuiz&action=show',
            Protocols::OPENTTD => 'steam://connect/{IP}:{C_PORT}',
            Protocols::PAINKILLER => 'qtracker://{IP}:{S_PORT}?game=Painkiller&action=show',
            Protocols::PLAINSIGHT => 'http://www.plainsightgame.com',
            Protocols::PREY => 'qtracker://{IP}:{S_PORT}?game=Prey&action=show',
            Protocols::QUAKEWORLD => 'qtracker://{IP}:{S_PORT}?game=QuakeWorld&action=show',
            Protocols::QUAKEWARS => 'qtracker://{IP}:{S_PORT}?game=EnemyTerritoryQuakeWars&action=show',
            Protocols::QUAKE2 => 'qtracker://{IP}:{S_PORT}?game=Quake2&action=show',
            Protocols::QUAKE3 => 'qtracker://{IP}:{S_PORT}?game=Quake3&action=show',
            Protocols::QUAKE4 => 'qtracker://{IP}:{S_PORT}?game=Quake4&action=show',
            Protocols::RAGEMP => 'rage://v/connect?ip={IP}:{C_PORT}',
            Protocols::RAVENSHIELD => "http://en.wikipedia.org/wiki/Tom_Clancy's_Rainbow_Six_3",
            Protocols::REDORCHESTRA => 'steam://connect/{IP}:{C_PORT}',
            Protocols::RFACTOR => 'rfactor://{IP}:{C_PORT}',
            Protocols::SAMP => 'samp://{IP}:{C_PORT}',
            Protocols::SAVAGE => 'http://en.wikipedia.org/wiki/Savage:_The_Battle_for_Newerth',
            Protocols::SAVAGE2 => 'http://en.wikipedia.org/wiki/Savage_2:_A_Tortured_Soul',
            Protocols::SERIOUSSAM => 'qtracker://{IP}:{S_PORT}?game=SeriousSam&action=show',
            Protocols::SERIOUSSAM2 => 'qtracker://{IP}:{S_PORT}?game=Serious_Sam2&action=show',
            Protocols::SCUM => 'steam://connect/{IP}:{C_PORT}',
            Protocols::SF => 'steam://connect/{IP}:{C_PORT}',
            Protocols::SATISFACTORY => 'steam://connect/{IP}:{C_PORT}',
            Protocols::SHATTEREDHORIZON => 'http://en.wikipedia.org/wiki/Shattered_Horizon',
            Protocols::SOLDIEROFFORTUNE2 => 'qtracker://{IP}:{S_PORT}?game=SoldierOfFortune2&action=show',
            Protocols::SOLDAT => 'soldat://{IP}:{C_PORT}',
            Protocols::SOURCE => 'steam://connect/{IP}:{C_PORT}',
            Protocols::CS16 => 'steam://connect/{IP}:{C_PORT}',
            Protocols::CSGO => 'steam://connect/{IP}:{C_PORT}',
            Protocols::STALKER => 'qtracker://{IP}:{S_PORT}?game=STALKER_ShadowChernobyl&action=show',
            Protocols::STALKERCOP => 'qtracker://{IP}:{S_PORT}?game=STALKER_CallOfPripyat&action=show',
            Protocols::STALKERCS => 'qtracker://{IP}:{S_PORT}?game=STALKER_ClearSky&action=show',
            Protocols::STARTREKEF => 'http://en.wikipedia.org/wiki/Star_Trek:_Voyager:_Elite_Force',
            Protocols::STARWARSBF => 'qtracker://{IP}:{S_PORT}?game=StarWarsBattlefront&action=show',
            Protocols::STARWARSBF2 => 'qtracker://{IP}:{S_PORT}?game=StarWarsBattlefront2&action=show',
            Protocols::STARWARSRC => 'qtracker://{IP}:{S_PORT}?game=StarWarsRepublicCommando&action=show',
            Protocols::SWAT4 => 'qtracker://{IP}:{S_PORT}?game=SWAT4&action=show',
            Protocols::TEST => 'http://www.greycube.com',
            Protocols::TEENWORLDS => 'steam://connect/{IP}:{C_PORT}',
            Protocols::TERRARIA => 'steam://connect/{IP}:{C_PORT}',
            Protocols::TRIBES => 'qtracker://{IP}:{S_PORT}?game=Tribes&action=show',
            Protocols::TRIBES2 => 'qtracker://{IP}:{S_PORT}?game=Tribes2&action=show',
            Protocols::TRIBESV => 'qtracker://{IP}:{S_PORT}?game=TribesVengeance&action=show',
            Protocols::TS => 'http://www.teamspeak.com',
            Protocols::TEAMSPEAK => 'http://www.teamspeak.com',
            Protocols::TS3 => 'ts3server://{IP}?port={C_PORT}',
            Protocols::TEAMSPEAK3 => 'ts3server://{IP}?port={C_PORT}',
            Protocols::TEASPEAK => 'ts3server://{IP}?port={C_PORT}',
            Protocols::URBANTERROR => 'qtracker://{IP}:{S_PORT}?game=UrbanTerror&action=show',
            Protocols::UNREALTOURNAMENT => 'qtracker://{IP}:{S_PORT}?game=UnrealTournament&action=show',
            Protocols::UNREALTOURNAMENT2003 => 'qtracker://{IP}:{S_PORT}?game=UnrealTournament2003&action=show',
            Protocols::UNREALTOURNAMENT2004 => 'qtracker://{IP}:{S_PORT}?game=UnrealTournament2004&action=show',
            Protocols::UNREALTOURNAMENT3 => 'qtracker://{IP}:{S_PORT}?game=UnrealTournament3&action=show',
            Protocols::VCMP => 'https://vc-mp.org',
            Protocols::VIETCONG => 'qtracker://{IP}:{S_PORT}?game=Vietcong&action=show',
            Protocols::VIETCONG2 => 'qtracker://{IP}:{S_PORT}?game=Vietcong2&action=show',
            Protocols::WARSOW => 'warsow://{IP}:{C_PORT}',
            Protocols::WARSOWOLD => 'qtracker://{IP}:{S_PORT}?game=Warsow&action=show',
            Protocols::WOLFENSTEINET => 'qtracker://{IP}:{S_PORT}?game=WolfensteinEnemyTerritory&action=show',
            Protocols::WOLFENSTEINFRTCW => 'qtracker://{IP}:{S_PORT}?game=ReturntoCastleWolfenstein&action=show',
            Protocols::WOLFENSTEIN2009 => 'http://en.wikipedia.org/wiki/Wolfenstein_(2009_video_game)',
            Protocols::WOW => "javascript:prompt('Put it into your realm list:', 'set realmlist {IP}')",
        ];

        // SOFTWARE PORT IS THE QUERY PORT UNLESS SET
        if (! $s_port) {
            $s_port = $q_port;
        }

        // TRY USING THE STANDARD LAUNCH LINK FOR ALTERNATE PROTOCOLS IF ONE IS NOT SET
        if (! isset($links[$type])) {
            $type = str_replace('_', '', $type);
        }

        // INSERT DATA INTO STATIC LINK - CONVERT SPECIAL CHARACTERS - RETURN
        return htmlentities(
            str_replace(
                ['{IP}', '{C_PORT}', '{Q_PORT}', '{S_PORT}'],
                [$ip, $c_port, $q_port, $s_port],
                $links[$type]
            ),
            ENT_QUOTES
        );
    }
}
