<?php

namespace ZekyWolf\LGSQ\Helpers;

class SoftwareLink
{
    public static function get(string $type, string $ip, int $c_port, int $q_port, int $s_port): string
    {
        $links = [
            'aarmy' => 'qtracker://{IP}:{S_PORT}?game=ArmyOperations&action=show',
            'aarmy3' => 'qtracker://{IP}:{S_PORT}?game=AmericasArmy3&action=show',
            'arcasimracing' => 'http://en.wikipedia.org/wiki/ARCA_Sim_Racing',
            'arma' => 'qtracker://{IP}:{S_PORT}?game=ArmedAssault&action=show',
            'arma2' => 'http://en.wikipedia.org/wiki/ARMA_2',
            'arma3' => 'steam://connect/{IP}:{C_PORT}',
            'avp2' => 'qtracker://{IP}:{S_PORT}?game=AliensversusPredator2&action=show',
            'avp2010' => 'http://en.wikipedia.org/wiki/Aliens_vs._Predator_%28video_game%29',
            'bfbc2' => 'http://en.wikipedia.org/wiki/Battlefield_bad_company_2',
            'bfvietnam' => 'qtracker://{IP}:{S_PORT}?game=BattlefieldVietnam&action=show',
            'bf1942' => 'qtracker://{IP}:{S_PORT}?game=Battlefield1942&action=show',
            'bf2' => 'qtracker://{IP}:{S_PORT}?game=Battlefield2&action=show',
            'bf3' => 'https://en.wikipedia.org/wiki/Battlefield_3',
            'bf4' => 'https://en.wikipedia.org/wiki/Battlefield_4',
            'bf2142' => 'qtracker://{IP}:{S_PORT}?game=Battlefield2142&action=show',
            'callofduty' => 'qtracker://{IP}:{S_PORT}?game=CallOfDuty&action=show',
            'callofdutybo3' => 'qtracker://{IP}:{S_PORT}?game=CallOfDutyBlackOps3&action=show',
            'callofdutyiw' => "javascript:prompt('Put it into console:', 'connect {IP}:{C_PORT}')",
            'callofdutyuo' => 'qtracker://{IP}:{S_PORT}?game=CallOfDutyUnitedOffensive&action=show',
            'callofdutywaw' => 'qtracker://{IP}:{S_PORT}?game=CallOfDutyWorldAtWar&action=show',
            'callofduty2' => 'qtracker://{IP}:{S_PORT}?game=CallOfDuty2&action=show',
            'callofduty4' => 'cod4://{IP}:{S_PORT}',
            'cncrenegade' => 'qtracker://{IP}:{S_PORT}?game=CommandConquerRenegade&action=show',
            'conanexiles' => 'steam://connect/{IP}:{C_PORT}',
            'crysis' => 'qtracker://{IP}:{S_PORT}?game=Crysis&action=show',
            'crysiswars' => 'qtracker://{IP}:{S_PORT}?game=CrysisWars&action=show',
            'cs2d' => 'steam://connect/{IP}:{C_PORT}',
            'cube' => 'http://cubeengine.com',
            'discord' => 'https://discord.gg/{IP}',
            'doomskulltag' => 'http://skulltag.com',
            'doomzdaemon' => 'http://www.zdaemon.org',
            'doom3' => 'qtracker://{IP}:{S_PORT}?game=Doom3&action=show',
            'dh2005' => 'http://en.wikipedia.org/wiki/Deer_Hunter_(computer_game)',
            'eco' => 'http://{IP}:{Q_PORT}',
            'factorio' => 'steam://connect/{IP}',
            'farcry' => 'qtracker://{IP}:{S_PORT}?game=FarCry&action=show',
            'farmsim' => 'steam://connect/{IP}:{C_PORT}',
            'fear' => 'qtracker://{IP}:{S_PORT}?game=FEAR&action=show',
            'fivem' => 'fivem://connect/{IP}:{C_PORT}',
            'flashpoint' => 'qtracker://{IP}:{S_PORT}?game=OperationFlashpoint&action=show',
            'freelancer' => 'http://en.wikipedia.org/wiki/Freelancer_(computer_game)',
            'frontlines' => 'http://en.wikipedia.org/wiki/Frontlines:_Fuel_of_War',
            'f1c9902' => 'http://en.wikipedia.org/wiki/EA_Sports_F1_Series',
            'gamespy1' => 'http://www.greycube.com',
            'gamespy2' => 'http://www.greycube.com',
            'gamespy3' => 'http://www.greycube.com',
            'ghostrecon' => "http://en.wikipedia.org/wiki/Tom_Clancy's_Ghost_Recon",
            'graw' => 'qtracker://{IP}:{S_PORT}?game=GhostRecon&action=show',
            'graw2' => "http://en.wikipedia.org/wiki/Tom_Clancy's_Ghost_Recon_Advanced_Warfighter_2",
            'gtr2' => 'http://en.wikipedia.org/wiki/GTR2',
            'had2' => 'http://en.wikipedia.org/wiki/Hidden_&_Dangerous_2',
            'halflife' => 'steam://connect/{IP}:{C_PORT}',
            'halflifewon' => 'steam://connect/{IP}:{C_PORT}',
            'halo' => 'qtracker://{IP}:{S_PORT}?game=Halo&action=show',
            'il2' => 'http://en.wikipedia.org/wiki/IL-2_Sturmovik_(game)',
            'jediknight2' => 'qtracker://{IP}:{S_PORT}?game=JediKnight2&action=show',
            'jediknightja' => 'qtracker://{IP}:{S_PORT}?game=JediKnightJediAcademy&action=show',
            'jc2mp' => 'steam://connect/{IP}:{C_PORT}',
            'killingfloor' => 'steam://connect/{IP}:{C_PORT}',
            'kingpin' => 'qtracker://{IP}:{S_PORT}?game=Kingpin&action=show',
            'm2mp' => 'https://m2mp.de/',
            'minecraft' => 'minecraft://{IP}:{C_PORT}/',
            'mohaa' => 'qtracker://{IP}:{S_PORT}?game=MedalofHonorAlliedAssault&action=show',
            'mohaab' => 'qtracker://{IP}:{S_PORT}?game=MedalofHonorAlliedAssaultBreakthrough&action=show',
            'mohaas' => 'qtracker://{IP}:{S_PORT}?game=MedalofHonorAlliedAssaultSpearhead&action=show',
            'mohpa' => 'qtracker://{IP}:{S_PORT}?game=MedalofHonorPacificAssault&action=show',
            'mta' => 'mtasa://{IP}:{C_PORT}',
            'mumble' => 'mumble://{IP}/',
            'nascar2004' => 'http://en.wikipedia.org/wiki/NASCAR_Thunder_2004',
            'neverwinter' => 'qtracker://{IP}:{S_PORT}?game=NeverwinterNights&action=show',
            'neverwinter2' => 'qtracker://{IP}:{S_PORT}?game=NeverwinterNights&action=show',
            'nexuiz' => 'qtracker://{IP}:{S_PORT}?game=Nexuiz&action=show',
            'openttd' => 'steam://connect/{IP}:{C_PORT}',
            'painkiller' => 'qtracker://{IP}:{S_PORT}?game=Painkiller&action=show',
            'plainsight' => 'http://www.plainsightgame.com',
            'prey' => 'qtracker://{IP}:{S_PORT}?game=Prey&action=show',
            'quakeworld' => 'qtracker://{IP}:{S_PORT}?game=QuakeWorld&action=show',
            'quakewars' => 'qtracker://{IP}:{S_PORT}?game=EnemyTerritoryQuakeWars&action=show',
            'quake2' => 'qtracker://{IP}:{S_PORT}?game=Quake2&action=show',
            'quake3' => 'qtracker://{IP}:{S_PORT}?game=Quake3&action=show',
            'quake4' => 'qtracker://{IP}:{S_PORT}?game=Quake4&action=show',
            'ragemp' => 'rage://v/connect?ip={IP}:{C_PORT}',
            'ravenshield' => "http://en.wikipedia.org/wiki/Tom_Clancy's_Rainbow_Six_3",
            'redorchestra' => 'steam://connect/{IP}:{C_PORT}',
            'rfactor' => 'rfactor://{IP}:{C_PORT}',
            'samp' => 'samp://{IP}:{C_PORT}',
            'savage' => 'http://en.wikipedia.org/wiki/Savage:_The_Battle_for_Newerth',
            'savage2' => 'http://en.wikipedia.org/wiki/Savage_2:_A_Tortured_Soul',
            'serioussam' => 'qtracker://{IP}:{S_PORT}?game=SeriousSam&action=show',
            'serioussam2' => 'qtracker://{IP}:{S_PORT}?game=Serious_Sam2&action=show',
            'scum' => 'steam://connect/{IP}:{C_PORT}',
            'sf' => 'steam://connect/{IP}:{C_PORT}',
            'shatteredh' => 'http://en.wikipedia.org/wiki/Shattered_Horizon',
            'sof2' => 'qtracker://{IP}:{S_PORT}?game=SoldierOfFortune2&action=show',
            'soldat' => 'soldat://{IP}:{C_PORT}',
            'source' => 'steam://connect/{IP}:{C_PORT}',
            'stalker' => 'qtracker://{IP}:{S_PORT}?game=STALKER_ShadowChernobyl&action=show',
            'stalkercop' => 'qtracker://{IP}:{S_PORT}?game=STALKER_CallOfPripyat&action=show',
            'stalkercs' => 'qtracker://{IP}:{S_PORT}?game=STALKER_ClearSky&action=show',
            'startrekef' => 'http://en.wikipedia.org/wiki/Star_Trek:_Voyager:_Elite_Force',
            'starwarsbf' => 'qtracker://{IP}:{S_PORT}?game=StarWarsBattlefront&action=show',
            'starwarsbf2' => 'qtracker://{IP}:{S_PORT}?game=StarWarsBattlefront2&action=show',
            'starwarsrc' => 'qtracker://{IP}:{S_PORT}?game=StarWarsRepublicCommando&action=show',
            'swat4' => 'qtracker://{IP}:{S_PORT}?game=SWAT4&action=show',
            'test' => 'http://www.greycube.com',
            'teeworlds' => 'steam://connect/{IP}:{C_PORT}',
            'terraria' => 'steam://connect/{IP}:{C_PORT}',
            'tribes' => 'qtracker://{IP}:{S_PORT}?game=Tribes&action=show',
            'tribes2' => 'qtracker://{IP}:{S_PORT}?game=Tribes2&action=show',
            'tribesv' => 'qtracker://{IP}:{S_PORT}?game=TribesVengeance&action=show',
            'ts' => 'http://www.teamspeak.com',
            'ts3' => 'ts3server://{IP}?port={C_PORT}',
            'teaspeak' => 'ts3server://{IP}?port={C_PORT}',
            'urbanterror' => 'qtracker://{IP}:{S_PORT}?game=UrbanTerror&action=show',
            'ut' => 'qtracker://{IP}:{S_PORT}?game=UnrealTournament&action=show',
            'ut2003' => 'qtracker://{IP}:{S_PORT}?game=UnrealTournament2003&action=show',
            'ut2004' => 'qtracker://{IP}:{S_PORT}?game=UnrealTournament2004&action=show',
            'ut3' => 'qtracker://{IP}:{S_PORT}?game=UnrealTournament3&action=show',
            'vcmp' => 'https://vc-mp.org',
            'vietcong' => 'qtracker://{IP}:{S_PORT}?game=Vietcong&action=show',
            'vietcong2' => 'qtracker://{IP}:{S_PORT}?game=Vietcong2&action=show',
            'warsow' => 'warsow://{IP}:{C_PORT}',
            'warsowold' => 'qtracker://{IP}:{S_PORT}?game=Warsow&action=show',
            'wolfet' => 'qtracker://{IP}:{S_PORT}?game=WolfensteinEnemyTerritory&action=show',
            'wolfrtcw' => 'qtracker://{IP}:{S_PORT}?game=ReturntoCastleWolfenstein&action=show',
            'wolf2009' => 'http://en.wikipedia.org/wiki/Wolfenstein_(2009_video_game)',
            'wow' => "javascript:prompt('Put it into your realm list:', 'set realmlist {IP}')",
        ];

        // SOFTWARE PORT IS THE QUERY PORT UNLESS SET
        if (! $s_port) {
            $s_port = $q_port;
        }

        // TRY USING THE STANDARD LAUNCH LINK FOR ALTERNATE PROTOCOLS IF ONE IS NOT SET
        if (! isset($links[$type])) {
            $type = str_replace('_', '', $type);
        }

        // INSERT DATA INTO STATIC LINK - CONVERT SPECIAL CHARACTERS - RETURN
        return htmlentities(
            str_replace(
                ['{IP}', '{C_PORT}', '{Q_PORT}', '{S_PORT}'],
                [$ip, $c_port, $q_port, $s_port],
                $links[$type]
            ),
            ENT_QUOTES
        );
    }
}
