<?php

namespace ZekyWolf\LGSQ\Helpers;

class SoftwareLink
{
    public static function get(string $type, string $ip, int $c_port, int $q_port, int $s_port): string
    {
        $links = [
            Games::AMERICASARMY => 'qtracker://{IP}:{S_PORT}?game=ArmyOperations&action=show',
            Games::AMERICASARMY3 => 'qtracker://{IP}:{S_PORT}?game=AmericasArmy3&action=show',
            Games::ARCASIMRACING => 'http://en.wikipedia.org/wiki/ARCA_Sim_Racing',
            Games::ARMA => 'qtracker://{IP}:{S_PORT}?game=ArmedAssault&action=show',
            Games::ARMA2 => 'http://en.wikipedia.org/wiki/ARMA_2',
            Games::ARMA3 => 'steam://connect/{IP}:{C_PORT}',
            Games::DAYZ => 'steam://connect/{IP}:{C_PORT}',
            Games::ALIENSVSPREDATOR2 => 'qtracker://{IP}:{S_PORT}?game=AliensversusPredator2&action=show',
            Games::ALIENSVSPREDATOR2_2010 => 'http://en.wikipedia.org/wiki/Aliens_vs._Predator_%28video_game%29',
            Games::BATTLEFIELDBADCOMPANY2 => 'http://en.wikipedia.org/wiki/Battlefield_bad_company_2',
            Games::BATTLEFIELDVIETNAM => 'qtracker://{IP}:{S_PORT}?game=BattlefieldVietnam&action=show',
            Games::BATTLEFIELD1942 => 'qtracker://{IP}:{S_PORT}?game=Battlefield1942&action=show',
            Games::BATTLEFIELD2 => 'qtracker://{IP}:{S_PORT}?game=Battlefield2&action=show',
            Games::BATTLEFIELD3 => 'https://en.wikipedia.org/wiki/Battlefield_3',
            Games::BATTLEFIELD4 => 'https://en.wikipedia.org/wiki/Battlefield_4',
            Games::BATTLEFIELD2142 => 'qtracker://{IP}:{S_PORT}?game=Battlefield2142&action=show',
            Games::CALLOFDUTY => 'qtracker://{IP}:{S_PORT}?game=CallOfDuty&action=show',
            Games::CALLOFDUTYBO3 => 'qtracker://{IP}:{S_PORT}?game=CallOfDutyBlackOps3&action=show',
            Games::CALLOFDUTYIW => "javascript:prompt('Put it into console:', 'connect {IP}:{C_PORT}')",
            Games::CALLOFDUTYOU => 'qtracker://{IP}:{S_PORT}?game=CallOfDutyUnitedOffensive&action=show',
            Games::CALLOFDUTYWAW => 'qtracker://{IP}:{S_PORT}?game=CallOfDutyWorldAtWar&action=show',
            Games::CALLOFDUTY2 => 'qtracker://{IP}:{S_PORT}?game=CallOfDuty2&action=show',
            Games::CALLOFDUTY4 => 'cod4://{IP}:{S_PORT}',
            Games::COMMANDANDCONQUER => 'qtracker://{IP}:{S_PORT}?game=CommandConquerRenegade&action=show',
            Games::CONANEXILES => 'steam://connect/{IP}:{C_PORT}',
            Games::CRYSIS => 'qtracker://{IP}:{S_PORT}?game=Crysis&action=show',
            Games::CRYSISWARS => 'qtracker://{IP}:{S_PORT}?game=CrysisWars&action=show',
            Games::CS2D => 'steam://connect/{IP}:{C_PORT}',
            Games::CUBE => 'http://cubeengine.com',
            Games::DISCORD => 'https://discord.gg/{IP}',
            Games::DOOMSSKULLTAG => 'http://skulltag.com',
            Games::DOOMZDEAMON => 'http://www.zdaemon.org',
            Games::DOOM3 => 'qtracker://{IP}:{S_PORT}?game=Doom3&action=show',
            Games::DEERHUNTER2005 => 'http://en.wikipedia.org/wiki/Deer_Hunter_(computer_game)',
            Games::ECO => 'http://{IP}:{Q_PORT}',
            Games::FACTORIO => 'steam://connect/{IP}',
            Games::FARCRY => 'qtracker://{IP}:{S_PORT}?game=FarCry&action=show',
            Games::FARMINGSIMULATOR => 'steam://connect/{IP}:{C_PORT}',
            Games::FEAR => 'qtracker://{IP}:{S_PORT}?game=FEAR&action=show',
            Games::FIVEM => 'fivem://connect/{IP}:{C_PORT}',
            Games::REDM => 'fivem://connect/{IP}:{C_PORT}',
            Games::OPERATIONFLASHPOINT => 'qtracker://{IP}:{S_PORT}?game=OperationFlashpoint&action=show',
            Games::FREELANCER => 'http://en.wikipedia.org/wiki/Freelancer_(computer_game)',
            Games::FRONTLINES => 'http://en.wikipedia.org/wiki/Frontlines:_Fuel_of_War',
            Games::F1CHALLENGE9902 => 'http://en.wikipedia.org/wiki/EA_Sports_F1_Series',
            Games::GENERICSPY1 => 'http://www.greycube.com',
            Games::GENERICSPY2 => 'http://www.greycube.com',
            Games::GENERICSPY3 => 'http://www.greycube.com',
            Games::GHOSTRECON => "http://en.wikipedia.org/wiki/Tom_Clancy's_Ghost_Recon",
            Games::GRAW => 'qtracker://{IP}:{S_PORT}?game=GhostRecon&action=show',
            Games::GRAW2 => "http://en.wikipedia.org/wiki/Tom_Clancy's_Ghost_Recon_Advanced_Warfighter_2",
            Games::GTR2 => 'http://en.wikipedia.org/wiki/GTR2',
            Games::HIDDENANDDANGEROUSE2 => 'http://en.wikipedia.org/wiki/Hidden_&_Dangerous_2',
            Games::HALFLIFE => 'steam://connect/{IP}:{C_PORT}',
            Games::HALFLIFEWON => 'steam://connect/{IP}:{C_PORT}',
            Games::HALO => 'qtracker://{IP}:{S_PORT}?game=Halo&action=show',
            Games::IL22STURMOVIK => 'http://en.wikipedia.org/wiki/IL-2_Sturmovik_(game)',
            Games::JEDIKNIGHT2 => 'qtracker://{IP}:{S_PORT}?game=JediKnight2&action=show',
            Games::JEDIKNIGHTJA => 'qtracker://{IP}:{S_PORT}?game=JediKnightJediAcademy&action=show',
            Games::JUSTCOUSE2MP => 'steam://connect/{IP}:{C_PORT}',
            Games::KILLINGFLOOR => 'steam://connect/{IP}:{C_PORT}',
            Games::KINGPIN => 'qtracker://{IP}:{S_PORT}?game=Kingpin&action=show',
            Games::MAFIA2MP => 'https://m2mp.de/',
            Games::MINECRAFT => 'minecraft://{IP}:{C_PORT}/',
            Games::MOHAA => 'qtracker://{IP}:{S_PORT}?game=MedalofHonorAlliedAssault&action=show',
            Games::MOHAAB => 'qtracker://{IP}:{S_PORT}?game=MedalofHonorAlliedAssaultBreakthrough&action=show',
            Games::MOHAAS => 'qtracker://{IP}:{S_PORT}?game=MedalofHonorAlliedAssaultSpearhead&action=show',
            Games::MOPHA => 'qtracker://{IP}:{S_PORT}?game=MedalofHonorPacificAssault&action=show',
            Games::MTA => 'mtasa://{IP}:{C_PORT}',
            Games::MUMBLE => 'mumble://{IP}/',
            Games::NASCAR2004 => 'http://en.wikipedia.org/wiki/NASCAR_Thunder_2004',
            Games::NEVERWINTER => 'qtracker://{IP}:{S_PORT}?game=NeverwinterNights&action=show',
            Games::NEVERWINTER2 => 'qtracker://{IP}:{S_PORT}?game=NeverwinterNights&action=show',
            Games::NEXUIZ => 'qtracker://{IP}:{S_PORT}?game=Nexuiz&action=show',
            Games::OPENTTD => 'steam://connect/{IP}:{C_PORT}',
            Games::PAINKILLER => 'qtracker://{IP}:{S_PORT}?game=Painkiller&action=show',
            Games::PLAINSIGHT => 'http://www.plainsightgame.com',
            Games::PREY => 'qtracker://{IP}:{S_PORT}?game=Prey&action=show',
            Games::QUAKEWORLD => 'qtracker://{IP}:{S_PORT}?game=QuakeWorld&action=show',
            Games::QUAKEWARS => 'qtracker://{IP}:{S_PORT}?game=EnemyTerritoryQuakeWars&action=show',
            Games::QUAKE2 => 'qtracker://{IP}:{S_PORT}?game=Quake2&action=show',
            Games::QUAKE3 => 'qtracker://{IP}:{S_PORT}?game=Quake3&action=show',
            Games::QUAKE4 => 'qtracker://{IP}:{S_PORT}?game=Quake4&action=show',
            Games::RAGEMP => 'rage://v/connect?ip={IP}:{C_PORT}',
            Games::RAVENSHIELD => "http://en.wikipedia.org/wiki/Tom_Clancy's_Rainbow_Six_3",
            Games::REDORCHESTRA => 'steam://connect/{IP}:{C_PORT}',
            Games::RFACTOR => 'rfactor://{IP}:{C_PORT}',
            Games::SAMP => 'samp://{IP}:{C_PORT}',
            Games::SAVAGE => 'http://en.wikipedia.org/wiki/Savage:_The_Battle_for_Newerth',
            Games::SAVAGE2 => 'http://en.wikipedia.org/wiki/Savage_2:_A_Tortured_Soul',
            Games::SERIOUSSAM => 'qtracker://{IP}:{S_PORT}?game=SeriousSam&action=show',
            Games::SERIOUSSAM2 => 'qtracker://{IP}:{S_PORT}?game=Serious_Sam2&action=show',
            Games::SCUM => 'steam://connect/{IP}:{C_PORT}',
            Games::SF => 'steam://connect/{IP}:{C_PORT}',
            Games::SATISFACTORY => 'steam://connect/{IP}:{C_PORT}',
            Games::SHATTEREDHORIZON => 'http://en.wikipedia.org/wiki/Shattered_Horizon',
            Games::SOLDIEROFFORTUNE2 => 'qtracker://{IP}:{S_PORT}?game=SoldierOfFortune2&action=show',
            Games::SOLDAT => 'soldat://{IP}:{C_PORT}',
            Games::SOURCE => 'steam://connect/{IP}:{C_PORT}',
            Games::STALKER => 'qtracker://{IP}:{S_PORT}?game=STALKER_ShadowChernobyl&action=show',
            Games::STALKERCOP => 'qtracker://{IP}:{S_PORT}?game=STALKER_CallOfPripyat&action=show',
            Games::STALKERCS => 'qtracker://{IP}:{S_PORT}?game=STALKER_ClearSky&action=show',
            Games::STARTREKEF => 'http://en.wikipedia.org/wiki/Star_Trek:_Voyager:_Elite_Force',
            Games::STARWARSBF => 'qtracker://{IP}:{S_PORT}?game=StarWarsBattlefront&action=show',
            Games::STARWARSBF2 => 'qtracker://{IP}:{S_PORT}?game=StarWarsBattlefront2&action=show',
            Games::STARWARSRC => 'qtracker://{IP}:{S_PORT}?game=StarWarsRepublicCommando&action=show',
            Games::SWAT4 => 'qtracker://{IP}:{S_PORT}?game=SWAT4&action=show',
            Games::TEST => 'http://www.greycube.com',
            Games::TEENWORLDS => 'steam://connect/{IP}:{C_PORT}',
            Games::TERRARIA => 'steam://connect/{IP}:{C_PORT}',
            Games::TRIBERS => 'qtracker://{IP}:{S_PORT}?game=Tribes&action=show',
            Games::TRIBERS2 => 'qtracker://{IP}:{S_PORT}?game=Tribes2&action=show',
            Games::TRIBERSV => 'qtracker://{IP}:{S_PORT}?game=TribesVengeance&action=show',
            Games::TS => 'http://www.teamspeak.com',
            Games::TS3 => 'ts3server://{IP}?port={C_PORT}',
            Games::TEASPEAK => 'ts3server://{IP}?port={C_PORT}',
            Games::URBANTERROR => 'qtracker://{IP}:{S_PORT}?game=UrbanTerror&action=show',
            Games::UNREALTOURNAMENT => 'qtracker://{IP}:{S_PORT}?game=UnrealTournament&action=show',
            Games::UNREALTOURNAMENT2003 => 'qtracker://{IP}:{S_PORT}?game=UnrealTournament2003&action=show',
            Games::UNREALTOURNAMENT2004 => 'qtracker://{IP}:{S_PORT}?game=UnrealTournament2004&action=show',
            Games::UNREALTOURNAMENT3 => 'qtracker://{IP}:{S_PORT}?game=UnrealTournament3&action=show',
            Games::VCMP => 'https://vc-mp.org',
            Games::VIETCONG => 'qtracker://{IP}:{S_PORT}?game=Vietcong&action=show',
            Games::VIETCONG2 => 'qtracker://{IP}:{S_PORT}?game=Vietcong2&action=show',
            Games::WARSOW => 'warsow://{IP}:{C_PORT}',
            Games::WARSOWOLD => 'qtracker://{IP}:{S_PORT}?game=Warsow&action=show',
            Games::WOLFENSTEINET => 'qtracker://{IP}:{S_PORT}?game=WolfensteinEnemyTerritory&action=show',
            Games::WOLFENSTEINFRTCW => 'qtracker://{IP}:{S_PORT}?game=ReturntoCastleWolfenstein&action=show',
            Games::WOLFENSTEIN2009 => 'http://en.wikipedia.org/wiki/Wolfenstein_(2009_video_game)',
            games::WOW => "javascript:prompt('Put it into your realm list:', 'set realmlist {IP}')",
        ];

        // SOFTWARE PORT IS THE QUERY PORT UNLESS SET
        if (! $s_port) {
            $s_port = $q_port;
        }

        // TRY USING THE STANDARD LAUNCH LINK FOR ALTERNATE PROTOCOLS IF ONE IS NOT SET
        if (! isset($links[$type])) {
            $type = str_replace('_', '', $type);
        }

        // INSERT DATA INTO STATIC LINK - CONVERT SPECIAL CHARACTERS - RETURN
        return htmlentities(
            str_replace(
                ['{IP}', '{C_PORT}', '{Q_PORT}', '{S_PORT}'],
                [$ip, $c_port, $q_port, $s_port],
                $links[$type]
            ),
            ENT_QUOTES
        );
    }
}
