<?php

namespace ZekyWolf\LGSQ\Helpers;

use ZekyWolf\LGSQ\Helpers\Protocols;

class TypeList
{
    public static function get(): array
    {
        return [
            Protocols::AMERICASARMY => 'Americas Army',
            Protocols::AMERICASARMY3 => 'Americas Army 3',
            Protocols::ARCASIMRACING => 'Arca Sim Racing',
            Protocols::ARMA => 'ArmA: Armed Assault',
            Protocols::ARMA2 => 'ArmA 2',
            Protocols::ARMA3 => 'ArmA 3 / DayZ',
            Protocols::ALIENSVSPREDATOR2 => 'Aliens VS. Predator 2',
            Protocols::ALIENSVSPREDATOR2_2010 => 'Aliens VS. Predator ( 2010 By Rebellion )',
            Protocols::BATTLEFIELDBADCOMPANY2 => 'Battlefield Bad Company 2',
            Protocols::BATTLEFIELDVIETNAM => 'Battlefield Vietnam',
            Protocols::BATTLEFIELD1942 => 'Battlefield 1942',
            Protocols::BATTLEFIELD2 => 'Battlefield 2',
            Protocols::BATTLEFIELD3 => 'Battlefield 3',
            Protocols::BATTLEFIELD4 => 'Battlefield 4',
            Protocols::BATTLEFIELD2142 => 'Battlefield 2142',
            Protocols::CALLOFDUTY => 'Call Of Duty',
            Protocols::CALLOFDUTYBO3 => 'Call Of Duty: Black Ops 3',
            Protocols::CALLOFDUTYIW => 'Call Of Duty (IW4, IW5, IW6x)',
            Protocols::CALLOFDUTYOU => 'Call Of Duty: United Offensive',
            Protocols::CALLOFDUTYWAW => 'Call Of Duty: World at War',
            Protocols::CALLOFDUTY2 => 'Call Of Duty 2',
            Protocols::CALLOFDUTY4 => 'Call Of Duty 4 / CoD4X',
            Protocols::COMMANDANDCONQUER => 'Command and Conquer: Renegade',
            Protocols::CONANEXILES => 'Conan Exiles',
            Protocols::CRYSIS => 'Crysis',
            Protocols::CRYSISWARS => 'Crysis Wars',
            Protocols::CS2D => 'Counter-Strike 2D',
            Protocols::CUBE => 'Cube Engine',
            Protocols::DISCORD => 'Discord',
            Protocols::DOOMSSKULLTAG => 'Doom - Skulltag',
            Protocols::DOOMZDEAMON => 'Doom - ZDaemon',
            Protocols::DOOM3 => 'Doom 3',
            Protocols::DEERHUNTER2005 => 'Deer Hunter 2005',
            Protocols::ECO => 'ECO',
            Protocols::FACTORIO => 'Factorio',
            Protocols::FARCRY => 'Far Cry',
            Protocols::FARMINGSIMULATOR => 'Farming Simulator',
            Protocols::FEAR => 'F.E.A.R.',
            Protocols::FIVEM => 'FiveM / RedM',
            Protocols::OPERATIONFLASHPOINT => 'Operation Flashpoint',
            Protocols::FREELANCER => 'Freelancer',
            Protocols::FRONTLINES => 'Frontlines: Fuel Of War',
            Protocols::F1CHALLENGE9902 => 'F1 Challenge 99-02',
            Protocols::GENERICSPY1 => 'Generic GameSpy 1',
            Protocols::GENERICSPY2 => 'Generic GameSpy 2',
            Protocols::GENERICSPY3 => 'Generic GameSpy 3',
            Protocols::GHOSTRECON => 'Ghost Recon',
            Protocols::GRAW => 'Ghost Recon: Advanced Warfighter',
            Protocols::GRAW2 => 'Ghost Recon: Advanced Warfighter 2',
            Protocols::GTR2 => 'GTR 2',
            Protocols::HIDDENANDDANGEROUSE2 => 'Hidden and Dangerous 2',
            Protocols::HALFLIFE => 'Half-life Steam Protocol (CS 1.6, etc)',
            Protocols::HALFLIFEWON => 'Half-Life WON Protocol [OLD] (CS 1.5)',
            Protocols::CS16 => 'Counter Strike 1.6',
            Protocols::CSGO => 'Counter Strike: Global Offensive',
            Protocols::HALO => 'Halo',
            Protocols::IL22STURMOVIK => 'IL-2 Sturmovik',
            Protocols::JEDIKNIGHT2 => 'JediKnight 2: Jedi Outcast',
            Protocols::JEDIKNIGHTJA => 'JediKnight: Jedi Academy',
            Protocols::JUSTCOUSE2MP => 'Just Cause 2 Multiplayer',
            Protocols::KILLINGFLOOR => 'Killing Floor',
            Protocols::KINGPIN => 'Kingpin: Life of Crime',
            Protocols::MAFIA2MP => 'Mafia II Multiplayer',
            Protocols::MINECRAFT => 'Minecraft',
            Protocols::MOHAA => 'Medal of Honor: Allied Assault',
            Protocols::MOHAAB => 'Medal of Honor: Allied Assault Breakthrough',
            Protocols::MOHAAS => 'Medal of Honor: Allied Assault Spearhead',
            Protocols::MOPHA => 'Medal of Honor: Pacific Assault',
            Protocols::MTA => 'Multi Theft Auto',
            Protocols::MUMBLE => 'Mumble',
            Protocols::NASCAR2004 => 'Nascar Thunder 2004',
            Protocols::NEVERWINTER => 'NeverWinter Nights',
            Protocols::NEVERWINTER2 => 'NeverWinter Nights 2',
            Protocols::NEXUIZ => 'Nexuiz',
            Protocols::OPENTTD => 'Open Transport Tycoon Deluxe',
            Protocols::PAINKILLER => 'PainKiller',
            Protocols::PLAINSIGHT => 'Plain Sight',
            Protocols::PREY => 'Prey',
            Protocols::QUAKEWORLD => 'Quake World',
            Protocols::QUAKEWARS => 'Enemy Territory: Quake Wars',
            Protocols::QUAKE2 => 'Quake 2',
            Protocols::QUAKE3 => 'Quake 3',
            Protocols::QUAKE4 => 'Quake 4',
            Protocols::RAGEMP => 'Rage:MP',
            Protocols::RAVENSHIELD => 'Raven Shield',
            Protocols::REDORCHESTRA => 'Red Orchestra',
            Protocols::RFACTOR => 'RFactor',
            Protocols::SAMP => 'San Andreas Multiplayer',
            Protocols::SAVAGE => 'Savage',
            Protocols::SAVAGE2 => 'Savage 2',
            Protocols::SCUM => 'SCUM',
            Protocols::SF => 'Satisfactory',
            Protocols::SERIOUSSAM => 'Serious Sam',
            Protocols::SERIOUSSAM2 => 'Serious Sam 2',
            Protocols::SHATTEREDHORIZON => 'Shattered Horizon',
            Protocols::SOLDIEROFFORTUNE2 => 'Soldier of Fortune 2',
            Protocols::SOLDAT => 'Soldat',
            Protocols::SOURCE => 'Source Protocol ( Half-Life 2, etc. )',
            Protocols::STALKER => 'S.T.A.L.K.E.R.',
            Protocols::STALKERCOP => 'S.T.A.L.K.E.R. Call of Pripyat',
            Protocols::STALKERCS => 'S.T.A.L.K.E.R. Clear Sky',
            Protocols::STARTREKEF => 'StarTrek Elite-Force',
            Protocols::STARWARSBF => 'Star Wars: Battlefront',
            Protocols::STARWARSBF2 => 'Star Wars: Battlefront 2',
            Protocols::STARWARSRC => 'Star Wars: Republic Commando',
            Protocols::SWAT4 => 'SWAT 4',
            Protocols::TEENWORLDS => 'Teeworlds',
            Protocols::TERRARIA => 'Terraria',
            Protocols::TRIBERS => 'Tribes ( Starsiege )',
            Protocols::TRIBERS2 => 'Tribes 2',
            Protocols::TRIBERSV => 'Tribes Vengeance',
            Protocols::TS => 'Teamspeak',
            Protocols::TS3 => 'Teamspeak 3',
            Protocols::TEAMSPEAK3 => 'Teamspeak 3',
            Protocols::TEASPEAK => 'Teaspeak',
            Protocols::URBANTERROR => 'UrbanTerror',
            Protocols::UNREALTOURNAMENT => 'Unreal Tournament',
            Protocols::UNREALTOURNAMENT2003 => 'Unreal Tournament 2003',
            Protocols::UNREALTOURNAMENT2004 => 'Unreal Tournament 2004',
            Protocols::UNREALTOURNAMENT3 => 'Unreal Tournament 3',
            Protocols::VCMP => 'Vice City Multiplayer',
            Protocols::VIETCONG => 'Vietcong',
            Protocols::VIETCONG2 => 'Vietcong 2',
            Protocols::WARSOW => 'Warsow',
            Protocols::WARSOWOLD => 'Warsow ( 0.4.2 and older )',
            Protocols::WOLFENSTEINET => 'Wolfenstein: Enemy Territory',
            Protocols::WOLFENSTEINFRTCW => 'Wolfenstein: Return To Castle Wolfenstein',
            Protocols::WOLFENSTEIN2009 => 'Wolfenstein ( 2009 By Raven )',
            Protocols::WOW => 'World of Warcraft',
            Protocols::TEST => '~ Test ( For PHP Developers )',
        ];
    }
}
